name: BcRp
version: 1.0
main: com.Sobki_.BcRp.Core
author: Sobki_
description: A Bending themed role play server.
commands:
    element:
        usage: /element
        description: Checks your element.
    spawnwater:
        usage: /spawnwater
        description: Spawns Water NPC at senders location.
    spawnearth:
        usage: /spawnearth
        description: Spawns Earth NPC at senders location.
    spawnfire:
        usage: /spawnfire
        description: Spawns Fire NPC at senders location.
    spawnair:
        usage: /spawnair
        description: Spawns Air NPC at senders location.
    spawnblacksmith:
        usage: /spawnblacksmith
        description: Spawns a Blacksmith at the senders location.
    resetelement:
        usage: /resetelement
        description: Resets your element.
    resetstats:
        usage: /resetstats
        description: Resets your stats.
    tp:
        usage: /tp <player> or /tp <player> <player>
        description: Teleports to the specified player.
    tphere:
        usage: tphere <player>
        description: Teleports specified player to senders location.
    gamemode:
        usage: /gamemode <gamemode> [player]
        description: Change player gamemode.
    gm:
        usage: /gm <gamemode> [player]
        description: Change player gamemode.
    gms:
        usage: /gms [player]
        description: Change player gamemode to survival.
    gmc:
        usage: /gmc [player]
        description: Change player gamemode to creative.
    gma:
        usage: /gma [player]
        description: Change player gamemode to adventure.
    god:
        usage: /god [player]
        descrption: Toggles God mode for targeted player.
    fly:
        usage: /fly [player]
        description: Toggles Fly mode for targeted player.
    givemoney:
        usage: /givemoney <nation> <type> <player> <amount>
        description: Gives money to specified player.
    skills:
        usage: /skills
        description: Opens Skills inventory.
    stats:
        usage: /stats
        description: Shows your stats.
    spawnzombie:
        usage: /spawnzombie <level> <amount>
        description: Spawns a zombie of specified level where the player is looking.
    zombies:
        usage: /zombies
        description: Displays all zombies available for spawning.
    spawnskeleton:
        usage: /spawnskeleton <level> <amount>
        description: Spawns a skeleton of specified level where the player is looking.
    skeletons:
        usage: /skeletons
        description: Displays all skeletons available for spawning.
    friend:
        usage: /friend <add/remove/list> <arguments>
        aliases: [f]
        description: Base command for Friends.
    isop:
        usage: /isop <player>
        description: Checks if specified player is an Operator.
    summonyufu:
        usage: /summonyufu
        description: Spawns Yu Fu.
    herbcraft:
        usage: /herbcraft
        description: Opens the herbalism crafting window.